name: Hello-World-Test

on: [pull_request]

jobs:
  build:
    name: Testing basic hello-world command
    runs-on: ubuntu-20.04
    steps:
      - name: clone-repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      - name: build-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
      - name: python-wheel
        run: |
          python setup.py bdist_wheel
      - name: financetoolbox-install
        run: |
          python -m pip install dist/financetoolbox*.whl
      - name: hello-world
        run: |
          financetoolbox hello
